on: [push]
jobs:
  aura_scan:
    runs-on: ubuntu-latest
    name: Scan the code with Aura
    steps:
      - name: aura scan
        id: aura_scan
        # This automatically generates the `aura_ci_report.sarif` file
        uses: SourceCode-AI/actions@master
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: aura_ci_report.sarif
